/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainPlayerRouteImport } from './routes/main-player/route'
import { Route as IndexImport } from './routes/index'
import { Route as MiniPlayerIndexImport } from './routes/mini-player/index'
import { Route as FullscreenPlayerIndexImport } from './routes/fullscreen-player/index'
import { Route as MainPlayerHomeIndexImport } from './routes/main-player/home/index'

// Create/Update Routes

const MainPlayerRouteRoute = MainPlayerRouteImport.update({
  id: '/main-player',
  path: '/main-player',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MiniPlayerIndexRoute = MiniPlayerIndexImport.update({
  id: '/mini-player/',
  path: '/mini-player/',
  getParentRoute: () => rootRoute,
} as any)

const FullscreenPlayerIndexRoute = FullscreenPlayerIndexImport.update({
  id: '/fullscreen-player/',
  path: '/fullscreen-player/',
  getParentRoute: () => rootRoute,
} as any)

const MainPlayerHomeIndexRoute = MainPlayerHomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => MainPlayerRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/main-player': {
      id: '/main-player'
      path: '/main-player'
      fullPath: '/main-player'
      preLoaderRoute: typeof MainPlayerRouteImport
      parentRoute: typeof rootRoute
    }
    '/fullscreen-player/': {
      id: '/fullscreen-player/'
      path: '/fullscreen-player'
      fullPath: '/fullscreen-player'
      preLoaderRoute: typeof FullscreenPlayerIndexImport
      parentRoute: typeof rootRoute
    }
    '/mini-player/': {
      id: '/mini-player/'
      path: '/mini-player'
      fullPath: '/mini-player'
      preLoaderRoute: typeof MiniPlayerIndexImport
      parentRoute: typeof rootRoute
    }
    '/main-player/home/': {
      id: '/main-player/home/'
      path: '/home'
      fullPath: '/main-player/home'
      preLoaderRoute: typeof MainPlayerHomeIndexImport
      parentRoute: typeof MainPlayerRouteImport
    }
  }
}

// Create and export the route tree

interface MainPlayerRouteRouteChildren {
  MainPlayerHomeIndexRoute: typeof MainPlayerHomeIndexRoute
}

const MainPlayerRouteRouteChildren: MainPlayerRouteRouteChildren = {
  MainPlayerHomeIndexRoute: MainPlayerHomeIndexRoute,
}

const MainPlayerRouteRouteWithChildren = MainPlayerRouteRoute._addFileChildren(
  MainPlayerRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main-player': typeof MainPlayerRouteRouteWithChildren
  '/fullscreen-player': typeof FullscreenPlayerIndexRoute
  '/mini-player': typeof MiniPlayerIndexRoute
  '/main-player/home': typeof MainPlayerHomeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main-player': typeof MainPlayerRouteRouteWithChildren
  '/fullscreen-player': typeof FullscreenPlayerIndexRoute
  '/mini-player': typeof MiniPlayerIndexRoute
  '/main-player/home': typeof MainPlayerHomeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/main-player': typeof MainPlayerRouteRouteWithChildren
  '/fullscreen-player/': typeof FullscreenPlayerIndexRoute
  '/mini-player/': typeof MiniPlayerIndexRoute
  '/main-player/home/': typeof MainPlayerHomeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/main-player'
    | '/fullscreen-player'
    | '/mini-player'
    | '/main-player/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/main-player'
    | '/fullscreen-player'
    | '/mini-player'
    | '/main-player/home'
  id:
    | '__root__'
    | '/'
    | '/main-player'
    | '/fullscreen-player/'
    | '/mini-player/'
    | '/main-player/home/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainPlayerRouteRoute: typeof MainPlayerRouteRouteWithChildren
  FullscreenPlayerIndexRoute: typeof FullscreenPlayerIndexRoute
  MiniPlayerIndexRoute: typeof MiniPlayerIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainPlayerRouteRoute: MainPlayerRouteRouteWithChildren,
  FullscreenPlayerIndexRoute: FullscreenPlayerIndexRoute,
  MiniPlayerIndexRoute: MiniPlayerIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/main-player",
        "/fullscreen-player/",
        "/mini-player/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/main-player": {
      "filePath": "main-player/route.tsx",
      "children": [
        "/main-player/home/"
      ]
    },
    "/fullscreen-player/": {
      "filePath": "fullscreen-player/index.tsx"
    },
    "/mini-player/": {
      "filePath": "mini-player/index.tsx"
    },
    "/main-player/home/": {
      "filePath": "main-player/home/index.tsx",
      "parent": "/main-player"
    }
  }
}
ROUTE_MANIFEST_END */
