/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainPlayerRouteRouteImport } from './routes/main-player/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MiniPlayerIndexRouteImport } from './routes/mini-player/index'
import { Route as FullscreenPlayerIndexRouteImport } from './routes/fullscreen-player/index'
import { Route as MainPlayerSongsIndexRouteImport } from './routes/main-player/songs/index'
import { Route as MainPlayerSettingsIndexRouteImport } from './routes/main-player/settings/index'
import { Route as MainPlayerSearchIndexRouteImport } from './routes/main-player/search/index'
import { Route as MainPlayerQueueIndexRouteImport } from './routes/main-player/queue/index'
import { Route as MainPlayerPlaylistsIndexRouteImport } from './routes/main-player/playlists/index'
import { Route as MainPlayerLyricsIndexRouteImport } from './routes/main-player/lyrics/index'
import { Route as MainPlayerHomeIndexRouteImport } from './routes/main-player/home/index'
import { Route as MainPlayerGenresIndexRouteImport } from './routes/main-player/genres/index'
import { Route as MainPlayerFoldersIndexRouteImport } from './routes/main-player/folders/index'
import { Route as MainPlayerArtistsIndexRouteImport } from './routes/main-player/artists/index'
import { Route as MainPlayerAlbumsIndexRouteImport } from './routes/main-player/albums/index'
import { Route as MainPlayerSongsSongIdRouteImport } from './routes/main-player/songs/$songId'
import { Route as MainPlayerPlaylistsHistoryRouteImport } from './routes/main-player/playlists/history'
import { Route as MainPlayerPlaylistsFavoritesRouteImport } from './routes/main-player/playlists/favorites'
import { Route as MainPlayerPlaylistsPlaylistIdRouteImport } from './routes/main-player/playlists/$playlistId'
import { Route as MainPlayerGenresGenreIdRouteImport } from './routes/main-player/genres/$genreId'
import { Route as MainPlayerFoldersFolderPathRouteImport } from './routes/main-player/folders/$folderPath'
import { Route as MainPlayerArtistsArtistIdRouteImport } from './routes/main-player/artists/$artistId'
import { Route as MainPlayerAlbumsAlbumIdRouteImport } from './routes/main-player/albums/$albumId'
import { Route as MainPlayerSearchAllIndexRouteImport } from './routes/main-player/search/all/index'
import { Route as MainPlayerLyricsEditorSongIdRouteImport } from './routes/main-player/lyrics/editor/$songId'

const MainPlayerRouteRoute = MainPlayerRouteRouteImport.update({
  id: '/main-player',
  path: '/main-player',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniPlayerIndexRoute = MiniPlayerIndexRouteImport.update({
  id: '/mini-player/',
  path: '/mini-player/',
  getParentRoute: () => rootRouteImport,
} as any)
const FullscreenPlayerIndexRoute = FullscreenPlayerIndexRouteImport.update({
  id: '/fullscreen-player/',
  path: '/fullscreen-player/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainPlayerSongsIndexRoute = MainPlayerSongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => MainPlayerRouteRoute,
} as any)
const MainPlayerSettingsIndexRoute = MainPlayerSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MainPlayerRouteRoute,
} as any)
const MainPlayerSearchIndexRoute = MainPlayerSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => MainPlayerRouteRoute,
} as any)
const MainPlayerQueueIndexRoute = MainPlayerQueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => MainPlayerRouteRoute,
} as any)
const MainPlayerPlaylistsIndexRoute =
  MainPlayerPlaylistsIndexRouteImport.update({
    id: '/playlists/',
    path: '/playlists/',
    getParentRoute: () => MainPlayerRouteRoute,
  } as any)
const MainPlayerLyricsIndexRoute = MainPlayerLyricsIndexRouteImport.update({
  id: '/lyrics/',
  path: '/lyrics/',
  getParentRoute: () => MainPlayerRouteRoute,
} as any)
const MainPlayerHomeIndexRoute = MainPlayerHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => MainPlayerRouteRoute,
} as any)
const MainPlayerGenresIndexRoute = MainPlayerGenresIndexRouteImport.update({
  id: '/genres/',
  path: '/genres/',
  getParentRoute: () => MainPlayerRouteRoute,
} as any)
const MainPlayerFoldersIndexRoute = MainPlayerFoldersIndexRouteImport.update({
  id: '/folders/',
  path: '/folders/',
  getParentRoute: () => MainPlayerRouteRoute,
} as any)
const MainPlayerArtistsIndexRoute = MainPlayerArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => MainPlayerRouteRoute,
} as any)
const MainPlayerAlbumsIndexRoute = MainPlayerAlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => MainPlayerRouteRoute,
} as any)
const MainPlayerSongsSongIdRoute = MainPlayerSongsSongIdRouteImport.update({
  id: '/songs/$songId',
  path: '/songs/$songId',
  getParentRoute: () => MainPlayerRouteRoute,
} as any)
const MainPlayerPlaylistsHistoryRoute =
  MainPlayerPlaylistsHistoryRouteImport.update({
    id: '/playlists/history',
    path: '/playlists/history',
    getParentRoute: () => MainPlayerRouteRoute,
  } as any)
const MainPlayerPlaylistsFavoritesRoute =
  MainPlayerPlaylistsFavoritesRouteImport.update({
    id: '/playlists/favorites',
    path: '/playlists/favorites',
    getParentRoute: () => MainPlayerRouteRoute,
  } as any)
const MainPlayerPlaylistsPlaylistIdRoute =
  MainPlayerPlaylistsPlaylistIdRouteImport.update({
    id: '/playlists/$playlistId',
    path: '/playlists/$playlistId',
    getParentRoute: () => MainPlayerRouteRoute,
  } as any)
const MainPlayerGenresGenreIdRoute = MainPlayerGenresGenreIdRouteImport.update({
  id: '/genres/$genreId',
  path: '/genres/$genreId',
  getParentRoute: () => MainPlayerRouteRoute,
} as any)
const MainPlayerFoldersFolderPathRoute =
  MainPlayerFoldersFolderPathRouteImport.update({
    id: '/folders/$folderPath',
    path: '/folders/$folderPath',
    getParentRoute: () => MainPlayerRouteRoute,
  } as any)
const MainPlayerArtistsArtistIdRoute =
  MainPlayerArtistsArtistIdRouteImport.update({
    id: '/artists/$artistId',
    path: '/artists/$artistId',
    getParentRoute: () => MainPlayerRouteRoute,
  } as any)
const MainPlayerAlbumsAlbumIdRoute = MainPlayerAlbumsAlbumIdRouteImport.update({
  id: '/albums/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => MainPlayerRouteRoute,
} as any)
const MainPlayerSearchAllIndexRoute =
  MainPlayerSearchAllIndexRouteImport.update({
    id: '/search/all/',
    path: '/search/all/',
    getParentRoute: () => MainPlayerRouteRoute,
  } as any)
const MainPlayerLyricsEditorSongIdRoute =
  MainPlayerLyricsEditorSongIdRouteImport.update({
    id: '/lyrics/editor/$songId',
    path: '/lyrics/editor/$songId',
    getParentRoute: () => MainPlayerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main-player': typeof MainPlayerRouteRouteWithChildren
  '/fullscreen-player': typeof FullscreenPlayerIndexRoute
  '/mini-player': typeof MiniPlayerIndexRoute
  '/main-player/albums/$albumId': typeof MainPlayerAlbumsAlbumIdRoute
  '/main-player/artists/$artistId': typeof MainPlayerArtistsArtistIdRoute
  '/main-player/folders/$folderPath': typeof MainPlayerFoldersFolderPathRoute
  '/main-player/genres/$genreId': typeof MainPlayerGenresGenreIdRoute
  '/main-player/playlists/$playlistId': typeof MainPlayerPlaylistsPlaylistIdRoute
  '/main-player/playlists/favorites': typeof MainPlayerPlaylistsFavoritesRoute
  '/main-player/playlists/history': typeof MainPlayerPlaylistsHistoryRoute
  '/main-player/songs/$songId': typeof MainPlayerSongsSongIdRoute
  '/main-player/albums': typeof MainPlayerAlbumsIndexRoute
  '/main-player/artists': typeof MainPlayerArtistsIndexRoute
  '/main-player/folders': typeof MainPlayerFoldersIndexRoute
  '/main-player/genres': typeof MainPlayerGenresIndexRoute
  '/main-player/home': typeof MainPlayerHomeIndexRoute
  '/main-player/lyrics': typeof MainPlayerLyricsIndexRoute
  '/main-player/playlists': typeof MainPlayerPlaylistsIndexRoute
  '/main-player/queue': typeof MainPlayerQueueIndexRoute
  '/main-player/search': typeof MainPlayerSearchIndexRoute
  '/main-player/settings': typeof MainPlayerSettingsIndexRoute
  '/main-player/songs': typeof MainPlayerSongsIndexRoute
  '/main-player/lyrics/editor/$songId': typeof MainPlayerLyricsEditorSongIdRoute
  '/main-player/search/all': typeof MainPlayerSearchAllIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main-player': typeof MainPlayerRouteRouteWithChildren
  '/fullscreen-player': typeof FullscreenPlayerIndexRoute
  '/mini-player': typeof MiniPlayerIndexRoute
  '/main-player/albums/$albumId': typeof MainPlayerAlbumsAlbumIdRoute
  '/main-player/artists/$artistId': typeof MainPlayerArtistsArtistIdRoute
  '/main-player/folders/$folderPath': typeof MainPlayerFoldersFolderPathRoute
  '/main-player/genres/$genreId': typeof MainPlayerGenresGenreIdRoute
  '/main-player/playlists/$playlistId': typeof MainPlayerPlaylistsPlaylistIdRoute
  '/main-player/playlists/favorites': typeof MainPlayerPlaylistsFavoritesRoute
  '/main-player/playlists/history': typeof MainPlayerPlaylistsHistoryRoute
  '/main-player/songs/$songId': typeof MainPlayerSongsSongIdRoute
  '/main-player/albums': typeof MainPlayerAlbumsIndexRoute
  '/main-player/artists': typeof MainPlayerArtistsIndexRoute
  '/main-player/folders': typeof MainPlayerFoldersIndexRoute
  '/main-player/genres': typeof MainPlayerGenresIndexRoute
  '/main-player/home': typeof MainPlayerHomeIndexRoute
  '/main-player/lyrics': typeof MainPlayerLyricsIndexRoute
  '/main-player/playlists': typeof MainPlayerPlaylistsIndexRoute
  '/main-player/queue': typeof MainPlayerQueueIndexRoute
  '/main-player/search': typeof MainPlayerSearchIndexRoute
  '/main-player/settings': typeof MainPlayerSettingsIndexRoute
  '/main-player/songs': typeof MainPlayerSongsIndexRoute
  '/main-player/lyrics/editor/$songId': typeof MainPlayerLyricsEditorSongIdRoute
  '/main-player/search/all': typeof MainPlayerSearchAllIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/main-player': typeof MainPlayerRouteRouteWithChildren
  '/fullscreen-player/': typeof FullscreenPlayerIndexRoute
  '/mini-player/': typeof MiniPlayerIndexRoute
  '/main-player/albums/$albumId': typeof MainPlayerAlbumsAlbumIdRoute
  '/main-player/artists/$artistId': typeof MainPlayerArtistsArtistIdRoute
  '/main-player/folders/$folderPath': typeof MainPlayerFoldersFolderPathRoute
  '/main-player/genres/$genreId': typeof MainPlayerGenresGenreIdRoute
  '/main-player/playlists/$playlistId': typeof MainPlayerPlaylistsPlaylistIdRoute
  '/main-player/playlists/favorites': typeof MainPlayerPlaylistsFavoritesRoute
  '/main-player/playlists/history': typeof MainPlayerPlaylistsHistoryRoute
  '/main-player/songs/$songId': typeof MainPlayerSongsSongIdRoute
  '/main-player/albums/': typeof MainPlayerAlbumsIndexRoute
  '/main-player/artists/': typeof MainPlayerArtistsIndexRoute
  '/main-player/folders/': typeof MainPlayerFoldersIndexRoute
  '/main-player/genres/': typeof MainPlayerGenresIndexRoute
  '/main-player/home/': typeof MainPlayerHomeIndexRoute
  '/main-player/lyrics/': typeof MainPlayerLyricsIndexRoute
  '/main-player/playlists/': typeof MainPlayerPlaylistsIndexRoute
  '/main-player/queue/': typeof MainPlayerQueueIndexRoute
  '/main-player/search/': typeof MainPlayerSearchIndexRoute
  '/main-player/settings/': typeof MainPlayerSettingsIndexRoute
  '/main-player/songs/': typeof MainPlayerSongsIndexRoute
  '/main-player/lyrics/editor/$songId': typeof MainPlayerLyricsEditorSongIdRoute
  '/main-player/search/all/': typeof MainPlayerSearchAllIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/main-player'
    | '/fullscreen-player'
    | '/mini-player'
    | '/main-player/albums/$albumId'
    | '/main-player/artists/$artistId'
    | '/main-player/folders/$folderPath'
    | '/main-player/genres/$genreId'
    | '/main-player/playlists/$playlistId'
    | '/main-player/playlists/favorites'
    | '/main-player/playlists/history'
    | '/main-player/songs/$songId'
    | '/main-player/albums'
    | '/main-player/artists'
    | '/main-player/folders'
    | '/main-player/genres'
    | '/main-player/home'
    | '/main-player/lyrics'
    | '/main-player/playlists'
    | '/main-player/queue'
    | '/main-player/search'
    | '/main-player/settings'
    | '/main-player/songs'
    | '/main-player/lyrics/editor/$songId'
    | '/main-player/search/all'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/main-player'
    | '/fullscreen-player'
    | '/mini-player'
    | '/main-player/albums/$albumId'
    | '/main-player/artists/$artistId'
    | '/main-player/folders/$folderPath'
    | '/main-player/genres/$genreId'
    | '/main-player/playlists/$playlistId'
    | '/main-player/playlists/favorites'
    | '/main-player/playlists/history'
    | '/main-player/songs/$songId'
    | '/main-player/albums'
    | '/main-player/artists'
    | '/main-player/folders'
    | '/main-player/genres'
    | '/main-player/home'
    | '/main-player/lyrics'
    | '/main-player/playlists'
    | '/main-player/queue'
    | '/main-player/search'
    | '/main-player/settings'
    | '/main-player/songs'
    | '/main-player/lyrics/editor/$songId'
    | '/main-player/search/all'
  id:
    | '__root__'
    | '/'
    | '/main-player'
    | '/fullscreen-player/'
    | '/mini-player/'
    | '/main-player/albums/$albumId'
    | '/main-player/artists/$artistId'
    | '/main-player/folders/$folderPath'
    | '/main-player/genres/$genreId'
    | '/main-player/playlists/$playlistId'
    | '/main-player/playlists/favorites'
    | '/main-player/playlists/history'
    | '/main-player/songs/$songId'
    | '/main-player/albums/'
    | '/main-player/artists/'
    | '/main-player/folders/'
    | '/main-player/genres/'
    | '/main-player/home/'
    | '/main-player/lyrics/'
    | '/main-player/playlists/'
    | '/main-player/queue/'
    | '/main-player/search/'
    | '/main-player/settings/'
    | '/main-player/songs/'
    | '/main-player/lyrics/editor/$songId'
    | '/main-player/search/all/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainPlayerRouteRoute: typeof MainPlayerRouteRouteWithChildren
  FullscreenPlayerIndexRoute: typeof FullscreenPlayerIndexRoute
  MiniPlayerIndexRoute: typeof MiniPlayerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/main-player': {
      id: '/main-player'
      path: '/main-player'
      fullPath: '/main-player'
      preLoaderRoute: typeof MainPlayerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mini-player/': {
      id: '/mini-player/'
      path: '/mini-player'
      fullPath: '/mini-player'
      preLoaderRoute: typeof MiniPlayerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fullscreen-player/': {
      id: '/fullscreen-player/'
      path: '/fullscreen-player'
      fullPath: '/fullscreen-player'
      preLoaderRoute: typeof FullscreenPlayerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main-player/songs/': {
      id: '/main-player/songs/'
      path: '/songs'
      fullPath: '/main-player/songs'
      preLoaderRoute: typeof MainPlayerSongsIndexRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/settings/': {
      id: '/main-player/settings/'
      path: '/settings'
      fullPath: '/main-player/settings'
      preLoaderRoute: typeof MainPlayerSettingsIndexRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/search/': {
      id: '/main-player/search/'
      path: '/search'
      fullPath: '/main-player/search'
      preLoaderRoute: typeof MainPlayerSearchIndexRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/queue/': {
      id: '/main-player/queue/'
      path: '/queue'
      fullPath: '/main-player/queue'
      preLoaderRoute: typeof MainPlayerQueueIndexRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/playlists/': {
      id: '/main-player/playlists/'
      path: '/playlists'
      fullPath: '/main-player/playlists'
      preLoaderRoute: typeof MainPlayerPlaylistsIndexRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/lyrics/': {
      id: '/main-player/lyrics/'
      path: '/lyrics'
      fullPath: '/main-player/lyrics'
      preLoaderRoute: typeof MainPlayerLyricsIndexRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/home/': {
      id: '/main-player/home/'
      path: '/home'
      fullPath: '/main-player/home'
      preLoaderRoute: typeof MainPlayerHomeIndexRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/genres/': {
      id: '/main-player/genres/'
      path: '/genres'
      fullPath: '/main-player/genres'
      preLoaderRoute: typeof MainPlayerGenresIndexRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/folders/': {
      id: '/main-player/folders/'
      path: '/folders'
      fullPath: '/main-player/folders'
      preLoaderRoute: typeof MainPlayerFoldersIndexRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/artists/': {
      id: '/main-player/artists/'
      path: '/artists'
      fullPath: '/main-player/artists'
      preLoaderRoute: typeof MainPlayerArtistsIndexRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/albums/': {
      id: '/main-player/albums/'
      path: '/albums'
      fullPath: '/main-player/albums'
      preLoaderRoute: typeof MainPlayerAlbumsIndexRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/songs/$songId': {
      id: '/main-player/songs/$songId'
      path: '/songs/$songId'
      fullPath: '/main-player/songs/$songId'
      preLoaderRoute: typeof MainPlayerSongsSongIdRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/playlists/history': {
      id: '/main-player/playlists/history'
      path: '/playlists/history'
      fullPath: '/main-player/playlists/history'
      preLoaderRoute: typeof MainPlayerPlaylistsHistoryRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/playlists/favorites': {
      id: '/main-player/playlists/favorites'
      path: '/playlists/favorites'
      fullPath: '/main-player/playlists/favorites'
      preLoaderRoute: typeof MainPlayerPlaylistsFavoritesRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/playlists/$playlistId': {
      id: '/main-player/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/main-player/playlists/$playlistId'
      preLoaderRoute: typeof MainPlayerPlaylistsPlaylistIdRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/genres/$genreId': {
      id: '/main-player/genres/$genreId'
      path: '/genres/$genreId'
      fullPath: '/main-player/genres/$genreId'
      preLoaderRoute: typeof MainPlayerGenresGenreIdRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/folders/$folderPath': {
      id: '/main-player/folders/$folderPath'
      path: '/folders/$folderPath'
      fullPath: '/main-player/folders/$folderPath'
      preLoaderRoute: typeof MainPlayerFoldersFolderPathRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/artists/$artistId': {
      id: '/main-player/artists/$artistId'
      path: '/artists/$artistId'
      fullPath: '/main-player/artists/$artistId'
      preLoaderRoute: typeof MainPlayerArtistsArtistIdRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/albums/$albumId': {
      id: '/main-player/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/main-player/albums/$albumId'
      preLoaderRoute: typeof MainPlayerAlbumsAlbumIdRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/search/all/': {
      id: '/main-player/search/all/'
      path: '/search/all'
      fullPath: '/main-player/search/all'
      preLoaderRoute: typeof MainPlayerSearchAllIndexRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
    '/main-player/lyrics/editor/$songId': {
      id: '/main-player/lyrics/editor/$songId'
      path: '/lyrics/editor/$songId'
      fullPath: '/main-player/lyrics/editor/$songId'
      preLoaderRoute: typeof MainPlayerLyricsEditorSongIdRouteImport
      parentRoute: typeof MainPlayerRouteRoute
    }
  }
}

interface MainPlayerRouteRouteChildren {
  MainPlayerAlbumsAlbumIdRoute: typeof MainPlayerAlbumsAlbumIdRoute
  MainPlayerArtistsArtistIdRoute: typeof MainPlayerArtistsArtistIdRoute
  MainPlayerFoldersFolderPathRoute: typeof MainPlayerFoldersFolderPathRoute
  MainPlayerGenresGenreIdRoute: typeof MainPlayerGenresGenreIdRoute
  MainPlayerPlaylistsPlaylistIdRoute: typeof MainPlayerPlaylistsPlaylistIdRoute
  MainPlayerPlaylistsFavoritesRoute: typeof MainPlayerPlaylistsFavoritesRoute
  MainPlayerPlaylistsHistoryRoute: typeof MainPlayerPlaylistsHistoryRoute
  MainPlayerSongsSongIdRoute: typeof MainPlayerSongsSongIdRoute
  MainPlayerAlbumsIndexRoute: typeof MainPlayerAlbumsIndexRoute
  MainPlayerArtistsIndexRoute: typeof MainPlayerArtistsIndexRoute
  MainPlayerFoldersIndexRoute: typeof MainPlayerFoldersIndexRoute
  MainPlayerGenresIndexRoute: typeof MainPlayerGenresIndexRoute
  MainPlayerHomeIndexRoute: typeof MainPlayerHomeIndexRoute
  MainPlayerLyricsIndexRoute: typeof MainPlayerLyricsIndexRoute
  MainPlayerPlaylistsIndexRoute: typeof MainPlayerPlaylistsIndexRoute
  MainPlayerQueueIndexRoute: typeof MainPlayerQueueIndexRoute
  MainPlayerSearchIndexRoute: typeof MainPlayerSearchIndexRoute
  MainPlayerSettingsIndexRoute: typeof MainPlayerSettingsIndexRoute
  MainPlayerSongsIndexRoute: typeof MainPlayerSongsIndexRoute
  MainPlayerLyricsEditorSongIdRoute: typeof MainPlayerLyricsEditorSongIdRoute
  MainPlayerSearchAllIndexRoute: typeof MainPlayerSearchAllIndexRoute
}

const MainPlayerRouteRouteChildren: MainPlayerRouteRouteChildren = {
  MainPlayerAlbumsAlbumIdRoute: MainPlayerAlbumsAlbumIdRoute,
  MainPlayerArtistsArtistIdRoute: MainPlayerArtistsArtistIdRoute,
  MainPlayerFoldersFolderPathRoute: MainPlayerFoldersFolderPathRoute,
  MainPlayerGenresGenreIdRoute: MainPlayerGenresGenreIdRoute,
  MainPlayerPlaylistsPlaylistIdRoute: MainPlayerPlaylistsPlaylistIdRoute,
  MainPlayerPlaylistsFavoritesRoute: MainPlayerPlaylistsFavoritesRoute,
  MainPlayerPlaylistsHistoryRoute: MainPlayerPlaylistsHistoryRoute,
  MainPlayerSongsSongIdRoute: MainPlayerSongsSongIdRoute,
  MainPlayerAlbumsIndexRoute: MainPlayerAlbumsIndexRoute,
  MainPlayerArtistsIndexRoute: MainPlayerArtistsIndexRoute,
  MainPlayerFoldersIndexRoute: MainPlayerFoldersIndexRoute,
  MainPlayerGenresIndexRoute: MainPlayerGenresIndexRoute,
  MainPlayerHomeIndexRoute: MainPlayerHomeIndexRoute,
  MainPlayerLyricsIndexRoute: MainPlayerLyricsIndexRoute,
  MainPlayerPlaylistsIndexRoute: MainPlayerPlaylistsIndexRoute,
  MainPlayerQueueIndexRoute: MainPlayerQueueIndexRoute,
  MainPlayerSearchIndexRoute: MainPlayerSearchIndexRoute,
  MainPlayerSettingsIndexRoute: MainPlayerSettingsIndexRoute,
  MainPlayerSongsIndexRoute: MainPlayerSongsIndexRoute,
  MainPlayerLyricsEditorSongIdRoute: MainPlayerLyricsEditorSongIdRoute,
  MainPlayerSearchAllIndexRoute: MainPlayerSearchAllIndexRoute,
}

const MainPlayerRouteRouteWithChildren = MainPlayerRouteRoute._addFileChildren(
  MainPlayerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainPlayerRouteRoute: MainPlayerRouteRouteWithChildren,
  FullscreenPlayerIndexRoute: FullscreenPlayerIndexRoute,
  MiniPlayerIndexRoute: MiniPlayerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
