name: "✨ Feature Request"
description: Suggest a new feature or improvement for Nora
title: "[Feature]: "
labels:
  - enhancement

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: Is your feature request related to a problem?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: It would be great if Nora could...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?

  - type: dropdown
    id: feature_area
    attributes:
      label: Feature Area
      options:
        - Synced Lyrics
        - Last.FM Support
        - Mini Player
        - Personalization
        - Other
      
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / References
      description: Attach sketches, screenshots, or references.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, use cases, or information.