[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=native"]

[target.aarch64-pc-windows-msvc]

[target.x86_64-apple-darwin]

[target.aarch64-apple-darwin]

[target.x86_64-unknown-linux-gnu]
