/* eslint-disable no-use-before-define */
// Generated by https://quicktype.io

export interface CoverArtArchieveAPI {
  images: Image[];
  release: string;
}

export interface Image {
  approved: boolean;
  back: boolean;
  comment: string;
  edit: number;
  front: boolean;
  id: number;
  image: string;
  thumbnails: Thumbnails;
  types: string[];
}

export interface Thumbnails {
  '250': string;
  '500': string;
  '1200': string;
  large: string;
  small: string;
}
