[package]
name = "audio-engine"
version = "0.1.0"
edition = "2021"
authors = ["Sandakan Nipunajith <adsandakannipunajith2003@outlook.com>"]
description = "Native Rust Audio Engine for Nora Music Player (cpal + symphonia + rubato)"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
napi = { version = "2.16.1", default-features = false, features = ["async", "napi4", "tokio_rt"] }
napi-derive = "2.16.1"
cpal = "0.15"
symphonia = { version = "0.5.4", features = ["all"] }
rubato = "0.16.1"
log = "0.4"
env_logger = "0.11"
lazy_static = "1.4"


[build-dependencies]
napi-build = "2.1.3"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
strip = "symbols"
