name: Lint & Format Check

on:
  # Trigger on pull requests
  pull_request:

  # Trigger manually
  workflow_dispatch:

jobs:
  lint-format-check:
    name: Lint & Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          check-latest: true
          cache: npm

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint --deny-warnings

      - name: Run formatters
        run: npm run format
