name: Run Tests

on:
  # Trigger on pull requests
  pull_request:

  # Trigger manually
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test
